# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1os_nldnaEdBXZ1zQUTOdMAbnhiC43Qmz
"""

import os
import tensorflow as tf
from tensorflow.keras.applications import VGG16
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Flatten, Dense, Dropout, BatchNormalization
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau
from sklearn.utils.class_weight import compute_class_weight
import numpy as np
from google.colab import drive

drive.mount('/content/drive')

TRAIN_PATH = '/content/drive/MyDrive/dataset/Train'
TEST_PATH  = '/content/drive/MyDrive/dataset/Test'
SAVE_DIR   = '/content/drive/MyDrive/model'
os.makedirs(SAVE_DIR, exist_ok=True)

IMG_SIZE   = (224, 224)
BATCH_SIZE = 32
NUM_CLASSES = 9


train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=40,
    zoom_range=0.2,
    width_shift_range=0.1,
    height_shift_range=0.1,
    shear_range=0.1,
    horizontal_flip=True,
    vertical_flip=True,
    fill_mode='nearest',
    validation_split=0.15
)

test_datagen = ImageDataGenerator(rescale=1./255)

train_data = train_datagen.flow_from_directory(
    TRAIN_PATH,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    subset='training',
    shuffle=True,
    seed=42,
)

val_data = train_datagen.flow_from_directory(
    TRAIN_PATH,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    subset='validation',
    shuffle=False,
    seed=42,
)

test_data = test_datagen.flow_from_directory(
    TEST_PATH,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=False,
)

class_indices = train_data.classes
class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(class_indices),
    y=class_indices
)
class_weight_dict = dict(enumerate(class_weights))
print("Class weights:", class_weight_dict)


base_model = VGG16(weights='imagenet', include_top=False, input_shape=(*IMG_SIZE, 3))
base_model.trainable = False
x = Flatten()(base_model.output)
x = Dense(256, activation='relu')(x)
x = BatchNormalization()(x)
x = Dropout(0.5)(x)
x = Dense(128, activation='relu')(x)
x = Dropout(0.3)(x)
output = Dense(NUM_CLASSES, activation='softmax')(x)

model = Model(inputs=base_model.input, outputs=output)

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
    loss='categorical_crossentropy',
    metrics=['accuracy', tf.keras.metrics.AUC(name='auc')]
)


callbacks = [
    EarlyStopping(
        monitor='val_loss', patience=10,
        restore_best_weights=True, verbose=1
    ),
    ModelCheckpoint(
        filepath=os.path.join(SAVE_DIR, 'best_vgg16_skin.keras'),
        monitor='val_auc', mode='max',
        save_best_only=True, verbose=1
    ),
    ReduceLROnPlateau(
        monitor='val_loss', factor=0.5,
        patience=5, min_lr=1e-7, verbose=1
    ),
]

history= model.fit(
    train_data,
    epochs=50,
    validation_data=val_data,
    class_weight=class_weight_dict,
    callbacks=callbacks,
)


for layer in base_model.layers[-8:]:
    layer.trainable = True

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5),
    loss='categorical_crossentropy',
    metrics=['accuracy', tf.keras.metrics.AUC(name='auc')]
)

history_ft = model.fit(
    train_data,
    epochs=30,
    validation_data=val_data,
    class_weight=class_weight_dict,
    callbacks=callbacks,
)


loss, acc, auc = model.evaluate(test_data)
print(f"\nTest  →  loss: {loss:.4f} | accuracy: {acc:.4f} | AUC: {auc:.4f}")

model.save(os.path.join(SAVE_DIR, 'vgg16_skin_cancer_final.keras'))
print("Model saved!")

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns

# ── 1. Récupérer les prédictions ──────────────────────────────────────────────
test_data.reset()  # important : remet le générateur au début
y_pred_proba = model.predict(test_data, verbose=1)
y_pred = np.argmax(y_pred_proba, axis=1)
y_true = test_data.classes
class_names = list(test_data.class_indices.keys())
# ── 2. Matrice de confusion ───────────────────────────────────────────────────
cm = confusion_matrix(y_true, y_pred)
cm_norm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]

fig, axes = plt.subplots(1, 2, figsize=(18, 7))

# Matrice brute (nombres)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names, yticklabels=class_names,
            ax=axes[0], linewidths=0.5)
axes[0].set_title('Matrice de confusion (nombres)', fontsize=14, pad=12)
axes[0].set_xlabel('Classe prédite', fontsize=11)
axes[0].set_ylabel('Classe réelle', fontsize=11)
axes[0].tick_params(axis='x', rotation=45)
# Matrice normalisée (pourcentages)
sns.heatmap(cm_norm, annot=True, fmt='.2f', cmap='Blues',
            xticklabels=class_names, yticklabels=class_names,
            ax=axes[1], linewidths=0.5, vmin=0, vmax=1)
axes[1].set_title('Matrice de confusion (normalisée)', fontsize=14, pad=12)
axes[1].set_xlabel('Classe prédite', fontsize=11)
axes[1].set_ylabel('Classe réelle', fontsize=11)
axes[1].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.savefig('/content/drive/MyDrive/model/confusion_matrix.png', dpi=150, bbox_inches='tight')
plt.show()
# ── 3. Rapport de classification ──────────────────────────────────────────────
print("\n" + "="*60)
print("RAPPORT DE CLASSIFICATION")
print("="*60)
print(classification_report(y_true, y_pred, target_names=class_names))

# ── 4. Courbes d'entraînement (Phase 1 + Phase 2) ────────────────────────────
# Remplace ces valeurs par tes vraies métriques history.history[...] et history_ft.history[...]
# Si tu as bien sauvegardé history et history_ft, utilise directement :
# acc     = history.history['accuracy']     + history_ft.history['accuracy']
# val_acc = history.history['val_accuracy'] + history_ft.history['val_accuracy']
# etc.

acc     = history.history['accuracy']     + history_ft.history['accuracy']
val_acc = history.history['val_accuracy'] + history_ft.history['val_accuracy']
loss    = history.history['loss']         + history_ft.history['loss']
val_loss= history.history['val_loss']     + history_ft.history['val_loss']
auc     = history.history['auc']          + history_ft.history['auc']
val_auc = history.history['val_auc']      + history_ft.history['val_auc']
epochs  = range(1, len(acc) + 1)
# Ligne de séparation Phase 1 / Phase 2
sep = len(history.history['accuracy'])

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

for ax, train, val, title, ylabel in zip(
    axes,
    [acc, loss, auc],
    [val_acc, val_loss, val_auc],
    ['Accuracy', 'Loss', 'AUC'],
    ['Accuracy', 'Loss', 'AUC']
):
    ax.plot(epochs, train, 'b-o', markersize=3, label='Train', linewidth=1.5)
    ax.plot(epochs, val,   'r-o', markersize=3, label='Validation', linewidth=1.5)
    ax.axvline(x=sep, color='gray', linestyle='--', linewidth=1, label='Fine-tune start')
    ax.set_title(title, fontsize=13)
    ax.set_xlabel('Epoch')
    ax.set_ylabel(ylabel)
    ax.legend(fontsize=9)
    ax.grid(True, alpha=0.3)
    plt.suptitle('Courbes d\'entraînement — Phase 1 + Phase 2', fontsize=14, y=1.02)
plt.tight_layout()
plt.savefig('/content/drive/MyDrive/model/training_curves.png', dpi=150, bbox_inches='tight')
plt.show()
# ── 5. Accuracy par classe ────────────────────────────────────────────────────
per_class_acc = cm_norm.diagonal()

fig, ax = plt.subplots(figsize=(10, 5))
colors = ['#2196F3' if v >= 0.5 else '#F44336' for v in per_class_acc]
bars = ax.bar(class_names, per_class_acc, color=colors, edgecolor='white', linewidth=0.5)
ax.axhline(y=0.5, color='gray', linestyle='--', linewidth=1, label='Seuil 50%')
ax.set_ylim(0, 1)
ax.set_title('Accuracy par classe', fontsize=13)
ax.set_xlabel('Classe')
ax.set_ylabel('Accuracy')
ax.tick_params(axis='x', rotation=45)
for bar, val in zip(bars, per_class_acc):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.02,
            f'{val:.2f}', ha='center', va='bottom', fontsize=9)
    plt.tight_layout()
plt.savefig('/content/drive/MyDrive/model/per_class_accuracy.png', dpi=150, bbox_inches='tight')
plt.show()

print("\nTous les graphiques sauvegardés dans /content/drive/MyDrive/model/")